{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of /metrics requested",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Thead / goroutine Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"local-metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Internal Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(path, method, status) (rate(http_request_histogram_bucket{status=\"Internal Server Error\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count[$__rate_interval])) by (path, method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (path, method, status) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (path, method, status) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (path, method, status) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}